pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = 'mikelesnr'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: "${env.GITHUB_CREDENTIALS}", url: 'https://github.com/your-username/alx-backend-python.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    // Install dependencies using pip3
                    sh 'pip3 install -r messaging_app/requirements.txt'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    // Run tests using pytest and generate a report
                    sh 'pytest --junitxml=report.xml messaging_app/tests/'
                }
            }
        }
        stage('Publish Report') {
            steps {
                script {
                    // Publish test report
                    junit 'report.xml'
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'report.xml', allowEmptyArchive: true
        }
    }
}
