#!/bin/bash

# Apply blue deployment
kubectl apply -f blue_deployment.yaml
echo "Blue deployment applied."

# Apply green deployment
kubectl apply -f green_deployment.yaml
echo "Green deployment applied."

# Monitor logs for the green deployment
PODS=$(kubectl get pods -l app=messaging-app-green -o jsonpath='{.items[*].metadata.name}')

for POD in $PODS; do
  kubectl logs $POD
done
